### ISSUE TITLE
Integrate TravisCI for tests and checkstyle

### ISSUE THREAD

**Issue by whereswaldon** [JaysGitLab/cs5666-spr17-javatrix-ccubed#6]
See the documentation [here](https://docs.travis-ci.com/).
We should be able to have it both run our custom checkstyle and run our tests.

**Comment by campellcl** [comment]
It would appear that we do not have administrator rights to enable TravisCI. I think Dr. Fenwick would have to agree to make us admins. Do you believe that he will be willing to do this? Should I contact him on our group's behalf?

**Comment by whereswaldon** [comment]
I think we should ask.
@fenwickjb, can we have admin rights so that we can use Continuous Integration? Alternatively, can you enable it for us?
